sudo: required

services:
  - docker

language: node_js
node_js:
  - node

install:
  - case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;

script:
  - docker build . -t foobert/gc-query
    #- npm run coverage

deploy:
  provider: script
  script: bash bin/push.sh foobert/gc-query
  on:
    branch: master
