sudo: required

services:
- docker

language: node_js
node_js:
- node

script:
- docker build . -t foobert/gc-query
  #- npm run coverage

deploy:
  provider: script
  script: bash bin/push.sh foobert/gc-query
  on:
    branch: master
